#!/bin/sh

CATALOG=oml.catalog.xml
CONVERT=$HOME/Downloads/OMLConverters/bin/omlConverter
INPUT=oml-input
OUTPUT=ontologies
PUBLIC=$HOME/git/gov.nasa.jpl.imce.ontologies.public
PUBLIC_ONTOLOGIES=$PUBLIC/ontologies
PUBLIC_BUNDLES=$PUBLIC/bundles
IMCE=imce.jpl.nasa.gov
PROJECT_BUNDLE_PATH=$IMCE/foundation/project
EUROPA=europa.jpl.nasa.gov
OMG_ORG=www.omg.org
PURL_ORG=purl.org
W3_ORG=www.w3.org
OMIT="
  $OUTPUT/$IMCE/math
  $OUTPUT/$IMCE/skeleton
  $OUTPUT/$IMCE/discipline/mechanical
  $OUTPUT/$IMCE/discipline/ontological-behavior
  $OUTPUT/$IMCE/discipline/risk
  $OUTPUT/$IMCE/discipline/state-analysis
  $OUTPUT/$IMCE/foundation/owl2-mof2
  $OUTPUT/$IMCE/foundation/time
  $OUTPUT/$IMCE/oml/provenance
  $OUTPUT/$IMCE/$OMG_ORG
  $OUTPUT/$IMCE/*/*/*-embedding.owl
"

# run in analysis target/workflow/artifacts

if [ $(expr "$PWD" : '.*target\/workflow\/artifacts$') -eq 0 ]
then
  echo "must run in .../target/workflow/artifacts" 1>&2
  exit 1
fi

# copy exported function list data

rm -rf $INPUT
mkdir $INPUT
rsync -av $1/ $INPUT

# convert OML to owl

$CONVERT text $INPUT/$CATALOG --output $OUTPUT --owl --clear

# overwrite vocabulary with latest OWL files

rsync -av $PUBLIC_ONTOLOGIES/$IMCE $PUBLIC_ONTOLOGIES/$PURL_ORG $PUBLIC_ONTOLOGIES/$W3_ORG $OUTPUT

# add cached project bundle

mkdir -p $OUTPUT/$PROJECT_BUNDLE_PATH
rsync -av --exclude='**-embedding*' $PUBLIC_BUNDLES/$PROJECT_BUNDLE_PATH/ $OUTPUT/$PROJECT_BUNDLE_PATH

# omit unused vocabulary
rm -rf $OMIT
